name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
    - name: Configure
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: ctest --test-dir build
